apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: aeskeyapideployment
spec:
  replicas: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: aeskeyapi
        lang: golang
    spec:
      containers:
      - name: aeskeyapi
        image: bjd145/aeskeyapi:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: aeskeyapisvc
  labels:
    version: "1.0"
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  selector:
    app: aeskeyapi
  ports:
  - port: 80
    targetPort: 8081
  type: LoadBalancer
